### ISSUE TITLE
use staticfiles app 

### ISSUE THREAD

**Issue by chhantyal** [disqus/nexus#23]
https://docs.djangoproject.com/en/1.8/ref/contrib/staticfiles/

**Comment by Fluxx** [comment]
Is this a suggestion to *use* the static files app?  It's unclear since the description of the pull request is just a link.

**Comment by chhantyal** [comment]
yes, it is suggestion to use static files app.

**Comment by Fluxx** [comment]
Thanks for the suggestion, we will consider it.
